const { STATUS, ALL_STATUS } = require("./status");

const ENROLLMENT_STATUS = STATUS;
const DEFAULT_MONTHLY_CLASSES = 8;
const DEFAULT_EXTRA_MONTHLY_CLASSES = 0;
const ALL_ENROLLMENT_STATUS = ALL_STATUS;

module.exports = {
  ENROLLMENT_STATUS,
  DEFAULT_MONTHLY_CLASSES,
  DEFAULT_EXTRA_MONTHLY_CLASSES,
  ALL_ENROLLMENT_STATUS,
};
