const { STATUS, ALL_STATUS } = require("./status");

const RELATIONSHIP_STATUS = STATUS;
const DEFAULT_MONTHLY_CLASSES = 8;
const ALL_RELATIONSHIP_STATUS = ALL_STATUS;

module.exports = { RELATIONSHIP_STATUS, DEFAULT_MONTHLY_CLASSES, ALL_RELATIONSHIP_STATUS };
